server:
  port: 8080
spring:
  application:
    name: "rest-consumer-client"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
adapter:
  restconsumer:
    url: "http://localhost:8081/api"
